version: '3'

services:
  backend:
    build: ./backend
    container_name: django_az
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/usr/src/app
    ports:
      - 8000:8000
    depends_on:
      - arcadezonedb

  frontend:
    build: ./frontend
    container_name: frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - 5173:5173
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend

  arcadezonedb:
    image: postgres
    environment:
      - POSTGRES_DB=ArcadeZone
      - POSTGRES_USER=arcadezoneadmin
      - POSTGRES_PASSWORD=0000
    container_name: arcadezonedb
    ports:
      - "54320:5432"
    volumes:
      - arcadezonedbdata:/var/lib/postgresql/data/

volumes:
  arcadezonedbdata: